### ISSUE TITLE
Replace Personal Schedule ID row in PSCourses create page with dropdown menu

### ISSUE THREAD

**Issue by HansonYu23** [ucsb-cs156-f22/f22-7pm-courses#11]
Replace Personal Schedule ID row with Personal Schedule Dropdown menu, similar to Quarter dropdown menu in Personal Schedule create page. 

![Capture](https://user-images.githubusercontent.com/72899378/202703745-a5b7c502-b0ee-423d-a292-89d9ee40b46c.PNG)

Personal Schedule Dropdown menu will replace this:
![Capture2](https://user-images.githubusercontent.com/72899378/202703890-2599385f-6c0d-420f-813c-ddcdb0f44aa5.PNG)

When submit is clicked on the PSCourses create page the course associated with the enrollment code is added to the Personal Schedule selected in the dropdown menu.

**Comment by HansonYu23** [comment]
Please let me know if this is an issue that is good to proceed on. Thanks!

**Comment by pconrad** [comment]
Great issue!

Yes, this is what we want, exactly.  I think there's an issue to develop this component, exactly with this use case in mind.
